Move the Linux service to the main block
WorldWideTelescope/wwt-terraform-infra pull request #13
Opened 2020-12-03 22:29 UTC by pkgw

It wants to access Redis, etc., so it should all go together.

Also comment out the "datatier" storage, which isn't used in production. (There's probably a better variable-ier way to do this.)

I wanted to rename the current "wwt" service/plan to "communities" to reflect its reduced role, but Terraform would want to destroy and recreate the resources in order to do so, which I don't want to do even though the whole point of Terraform is that it's supposed to be safe ...

2020-12-03 23:56 UTC, coderandhiker requested changes
We cannot dual deploy Windows and Linux App Service Plans into the same Resource Group at this time.  This is on the roadmap: https://feedback.azure.com/forums/169385-web-apps/suggestions/37287583-allow-a-linux-and-windows-app-service-plan-to-exis

I recommend adding a new var.prefix-linux-resources resource group and updating the app service plan and app service to deploy into it.

2020-12-03 23:56 UTC, coderandhiker commented on website/.terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
@pkgw this should be excluded from your commit - add a record to your .gitignore for everything under .terraform and the .terraform.lock.hcl if the aren't in there already

2020-12-04 00:12 UTC, pkgw commented on website/.terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
@coderandhiker The Terraform CLI specifically instructs that these lockfiles should be kept in version control. I think it's a more recent thing, it only appeared when I upgraded my OS a week or two ago.

2020-12-04 00:13 UTC, coderandhiker commented on website/.terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
Ok, that's new to me - go ahead and add it back in

2020-12-04 01:45 UTC, coderandhiker approved these changes
I ran the revisions in my subscription and everything looks good now.

2020-12-04 02:03 UTC, merged